blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/owpz/ksuid/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/owpz/ksuid#readme
    about: Read the documentation and API reference
  - name: 🔧 Go Compatibility Validation
    url: https://github.com/owpz/ksuid/tree/main/docs/validation
    about: Tools for validating Go/TypeScript compatibility